# Generated by Django 4.2.11 on 2026-05-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_multi_branch'),
        ('preorder', '0009_remove_preorder_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preorders', to='branches.branch'),
        ),
    ]
