# Generated by Django 4.2.11 on 2026-05-11 08:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0010_multi_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorderproduct',
            old_name='selling_price',
            new_name='retail_price',
        ),
        migrations.AlterUniqueTogether(
            name='preordervariation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='preorderproduct',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='preordervariation',
            name='design_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preordervariation',
            unique_together={('preorder_product', 'design_name', 'color')},
        ),
        migrations.RemoveField(
            model_name='preordervariation',
            name='size',
        ),
    ]
