# Generated by Django 6.0.5 on 2026-06-12 13:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_homepage_content(apps, schema_editor):
    HomePageSettings = apps.get_model('ecommerce', 'HomePageSettings')
    ProductStatus = apps.get_model('ecommerce', 'ProductStatus')
    LandingPage = apps.get_model('ecommerce', 'LandingPage')
    LandingPageSection = apps.get_model('ecommerce', 'LandingPageSection')
    LandingPageCollageItem = apps.get_model('ecommerce', 'LandingPageCollageItem')

    # Get or create the main landing page
    landing_page, _ = LandingPage.objects.get_or_create(
        name="Main Storefront Home",
        defaults={"is_active": True}
    )

    try:
        hp_settings = HomePageSettings.objects.get(pk=1)
    except Exception:
        hp_settings = None

    if hp_settings:
        # 1. Migrate Hero Section (Draft)
        hero_section = LandingPageSection.objects.create(
            landing_page=landing_page,
            section_type='HERO',
            layout_variant='existing',
            display_order=0,
            is_active=True,
            status='DRAFT',
            config={
                "hero_badge_text": hp_settings.hero_badge_text or "New Collection 2024",
                "hero_heading_line1": hp_settings.hero_heading_line1 or "FIND",
                "hero_heading_line2": hp_settings.hero_heading_line2 or "CLOTHES",
                "hero_heading_line3": hp_settings.hero_heading_line3 or "THAT",
                "hero_heading_line4": hp_settings.hero_heading_line4 or "Matches",
                "hero_heading_line5": hp_settings.hero_heading_line5 or "YOUR STYLE",
                "hero_description": hp_settings.hero_description or "Browse through our diverse range of meticulously crafted garments...",
                "stat_brands": hp_settings.stat_brands or "200+",
                "stat_products": hp_settings.stat_products or "2,000+",
                "stat_customers": hp_settings.stat_customers or "30,000+"
            },
            image=hp_settings.hero_primary_image,
            mobile_image=hp_settings.hero_secondary_image
        )

        # 2. Migrate Category Collage (Draft)
        collage_section = LandingPageSection.objects.create(
            landing_page=landing_page,
            section_type='CATEGORY_COLLAGE',
            layout_variant='four-card-grid',
            display_order=10,
            is_active=hp_settings.collage_enabled,
            status='DRAFT',
            config={
                "collage_badge_text": hp_settings.collage_badge_text or "",
                "collage_heading": hp_settings.collage_heading or "",
                "collage_description": hp_settings.collage_description or "",
                "card_count": 4,
                "spacing": "medium"
            }
        )

        # Create collage items
        for i in range(1, 5):
            title = getattr(hp_settings, f"collage_card_{i}_title", "")
            subtitle = getattr(hp_settings, f"collage_card_{i}_subtitle", "")
            link = getattr(hp_settings, f"collage_card_{i}_link", "")
            image = getattr(hp_settings, f"collage_card_{i}_image", None)

            if title or link or image:
                LandingPageCollageItem.objects.create(
                    section=collage_section,
                    title_override=title,
                    link_override=link,
                    image=image,
                    display_order=i-1
                )

    # 3. Migrate Product Statuses to Product Sections (Draft)
    product_statuses = ProductStatus.objects.filter(display_on_home=True)
    for index, status in enumerate(product_statuses):
        LandingPageSection.objects.create(
            landing_page=landing_page,
            section_type='PRODUCT_SECTION',
            layout_variant='grid',
            display_order=20 + (status.display_order or index),
            is_active=status.is_active,
            status='DRAFT',
            config={
                "title": status.name,
                "status_slug": status.slug,
                "product_limit": 8,
                "layout": "grid",
                "view_all_link": f"/products?status={status.slug}"
            }
        )


def rollback_migration(apps, schema_editor):
    LandingPage = apps.get_model('ecommerce', 'LandingPage')
    LandingPage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_homepagesettings_collage_fields'),
        ('inventory', '0025_repair_design_color_galleries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section'), ('CATEGORY_COLLAGE', 'Category Collage'), ('AD_BANNER', 'Advertisement Banner'), ('PRODUCT_SECTION', 'Product Section')], max_length=50)),
                ('layout_variant', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing_pages/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='landing_pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ecommerce.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageProductSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_selections', to='ecommerce.landingpagesection')),
            ],
            options={
                'verbose_name': 'Landing Page Product Selection',
                'verbose_name_plural': 'Landing Page Product Selections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageCollageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=150, null=True)),
                ('link_override', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing_pages/collage/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('online_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.onlinecategory')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_items', to='ecommerce.landingpagesection')),
            ],
            options={
                'verbose_name': 'Landing Page Collage Item',
                'verbose_name_plural': 'Landing Page Collage Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_existing_homepage_content, rollback_migration),
    ]

