# Generated by Django 6.0.5 on 2026-07-22 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_landingpage_landingpagesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order total amount required to place an order', max_digits=10),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='min_product_buying_count',
            field=models.PositiveIntegerField(default=1, help_text='Minimum total quantity of products a customer must buy per order'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='footer_address',
            field=models.TextField(blank=True, default='সুরুজ মনোয়ারা শপিং কমপ্লেক্সের দোতালায়, বান্টি বাজার, আড়াইহাজার, নারায়ণগঞ্জ', help_text='Store address shown in the footer. Supports multiple lines.', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='footer_phone',
            field=models.CharField(blank=True, default='01896285447', help_text='Primary contact phone number for the footer.', max_length=50, null=True),
        ),
    ]
