# Generated by Django 6.0.5 on 2026-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_homepagesettings_min_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='min_unique_product_variants',
            field=models.PositiveIntegerField(default=1, help_text='Minimum unique product variants required in the cart to place an order'),
        ),
    ]
