# Generated by Django 6.0.5 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_homepagesettings_min_unique_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='min_product_buying_count',
            field=models.PositiveIntegerField(default=3, help_text='Minimum total quantity of products a customer must buy per order'),
        ),
    ]
