# Generated by Django 4.2.11 on 2026-05-08 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_branch_invoice_counter_branch_invoice_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(blank=True, default='', help_text="Role-based targeting (e.g. 'admin'). Empty = all roles.", max_length=20)),
                ('kind', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('DUE_PAYMENT', 'Due Payment'), ('ONLINE_PREORDER', 'Online Preorder'), ('LARGE_SALE', 'Large Sale'), ('STOCK_TRANSFER', 'Stock Transfer'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend path to navigate to on click, e.g. /sales/due', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='branches.branch')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Specific user recipient. If null, uses recipient_role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
