// Global sizes object
export const globalSizes = {
    pants: {
        men: {
            US: ["28", "30", "32", "34", "36", "38", "40", "42", "44"],
            EU: ["44", "46", "48", "50", "52", "54", "56", "58"],
            UK: ["28", "30", "32", "34", "36", "38", "40", "42"],
            Asia: ["M", "L", "XL", "XXL", "3XL"],
            international: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
        },
        women: {
            US: ["0", "2", "4", "6", "8", "10", "12", "14", "16"],
            EU: ["32", "34", "36", "38", "40", "42", "44", "46"],
            UK: ["4", "6", "8", "10", "12", "14", "16", "18"],
            Asia: ["S", "M", "L", "XL", "XXL"],
            international: ["XS", "S", "M", "L", "XL", "XXL"],
        },
    },
    shoes: {
        men: {
            US: ["6", "7", "8", "9", "10", "11", "12"],
            UK: ["5.5", "6.5", "7.5", "8.5", "9.5", "10.5"],
            EU: ["39", "40", "41", "42", "43", "44", "45"],
            Asia: ["240", "245", "250", "255", "260", "265", "270", "275", "280"], // mm
        },
        women: {
            US: ["5", "6", "7", "8", "9", "10"],
            UK: ["3", "4", "5", "6", "7"],
            EU: ["36", "37", "38", "39", "40", "41"],
            Asia: ["220", "225", "230", "235", "240", "245", "250"], // mm
        },
    },
    belts: {
        inches: ["28", "30", "32", "34", "36", "38", "40", "42"],
        cm: ["70", "75", "80", "85", "90", "95", "100", "105", "110"],
        Asia: ["S", "M", "L", "XL", "XXL"],
        international: ["S", "M", "L", "XL", "XXL"],
    },
    underwear: {
        men: {
            waistInches: ["28", "30", "32", "34", "36", "38"],
            international: ["XS", "S", "M", "L", "XL", "XXL"],
            Asia: ["M", "L", "XL", "XXL", "3XL"],
        },
        women: {
            dressSize: ["4", "6", "8", "10", "12"],
            international: ["XS", "S", "M", "L", "XL"],
            Asia: ["S", "M", "L", "XL", "XXL"],
        },
    },
    jersey: {
        men: {
            US: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            Asia: ["M", "L", "XL", "XXL", "3XL"],
            international: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
        },
        women: {
            US: ["XS", "S", "M", "L", "XL", "XXL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL"],
            Asia: ["S", "M", "L", "XL", "XXL"],
            international: ["XS", "S", "M", "L", "XL", "XXL"],
        },
    },
    shirts: {
        men: {
            US: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            Asia: ["M", "L", "XL", "XXL", "3XL"],
            international: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
        },
        women: {
            US: ["XS", "S", "M", "L", "XL", "XXL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL"],
            Asia: ["S", "M", "L", "XL", "XXL"],
            international: ["XS", "S", "M", "L", "XL", "XXL"],
        },
    },
    tshirts: {
        men: {
            US: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
            Asia: ["M", "L", "XL", "XXL", "3XL"],
            international: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
        },
        women: {
            US: ["XS", "S", "M", "L", "XL", "XXL"],
            UK: ["XS", "S", "M", "L", "XL", "XXL"],
            EU: ["XS", "S", "M", "L", "XL", "XXL"],
            Asia: ["S", "M", "L", "XL", "XXL"],
            international: ["XS", "S", "M", "L", "XL", "XXL"],
        },
    },
} as const;

// 100+ Curated Colors with exact HEX values across 9 distinct color families
export const COLORS = {
    // Blacks & Grays
    Black: "#000000",
    JetBlack: "#0A0A0A",
    Charcoal: "#36454F",
    DarkSlate: "#2F4F4F",
    Slate: "#708090",
    Gray: "#808080",
    Grey: "#808080",
    AshGray: "#B2BEB5",
    Silver: "#C0C0C0",
    LightGray: "#D3D3D3",
    Platinum: "#E5E4E2",
    Gunmetal: "#2A3439",

    // Whites & Creams
    White: "#FFFFFF",
    OffWhite: "#FAFAFA",
    Ivory: "#FFFFF0",
    Cream: "#FFFDD0",
    Beige: "#F5F5DC",
    Eggshell: "#F0EAD6",
    Pearl: "#FDEEF4",
    Alabaster: "#F0F8FF",
    Champagne: "#F7E7CE",
    Vanilla: "#F3E5AB",

    // Reds & Pinks
    Red: "#FF0000",
    Crimson: "#DC143C",
    Scarlet: "#FF2400",
    Ruby: "#E0115F",
    Maroon: "#800000",
    Burgundy: "#800020",
    Wine: "#722F37",
    BrickRed: "#CB4154",
    Coral: "#FF7F50",
    Pink: "#FFC0CB",
    LightPink: "#FFB6C1",
    HotPink: "#FF69B4",
    DeepPink: "#FF1493",
    Rose: "#FF007F",
    RoseGold: "#B76E79",
    Blush: "#DE5D83",
    Magenta: "#FF00FF",
    Fuchsia: "#C71585",
    Salmon: "#FA8072",
    Peach: "#FFDAB9",

    // Blues & Aquas
    Blue: "#0000FF",
    Navy: "#000080",
    MidnightBlue: "#191970",
    DarkBlue: "#00008B",
    RoyalBlue: "#4169E1",
    Cobalt: "#0047AB",
    Indigo: "#4B0082",
    SkyBlue: "#87CEEB",
    LightBlue: "#ADD8E6",
    BabyBlue: "#89CFF0",
    PowderBlue: "#B0E0E6",
    Cyan: "#00FFFF",
    Aqua: "#00FFFF",
    Turquoise: "#40E0D0",
    Teal: "#008080",
    SteelBlue: "#4682B4",
    Denim: "#1560BD",
    OceanBlue: "#0077BE",
    Sapphire: "#0F52BA",
    ElectricBlue: "#7DF9FF",

    // Greens & Olives
    Green: "#008000",
    DarkGreen: "#006400",
    ForestGreen: "#228B22",
    Emerald: "#50C878",
    Mint: "#98FF98",
    MintGreen: "#98FB98",
    Lime: "#00FF00",
    LimeGreen: "#32CD32",
    Olive: "#808000",
    OliveDrab: "#6B8E23",
    Sage: "#9DC183",
    Khaki: "#F0E68C",
    ArmyGreen: "#4B5320",
    Seafoam: "#9FE2BF",
    Jade: "#00A86B",
    Pistachio: "#93C572",
    HunterGreen: "#355E3B",

    // Purples & Violets
    Purple: "#800080",
    Violet: "#8A2BE2",
    Lavender: "#E6E6FA",
    Plum: "#8E4585",
    Lilac: "#C8A2C8",
    Mauve: "#E0B0FF",
    Eggplant: "#614051",
    Amethyst: "#9966CC",
    Grape: "#6F2DA8",
    Orchid: "#DA70D6",
    Periwinkle: "#CCCCFF",

    // Yellows & Oranges
    Yellow: "#FFFF00",
    Lemon: "#FFF700",
    Gold: "#FFD700",
    Mustard: "#FFDB58",
    Amber: "#FFBF00",
    Orange: "#FFA500",
    DarkOrange: "#FF8C00",
    CoralOrange: "#FF6F61",
    Tangerine: "#F28500",
    BurntOrange: "#CC5500",
    Rust: "#B7410E",
    Apricot: "#FBCEB1",
    Honey: "#EB9605",

    // Browns & Earth Tones
    Brown: "#A52A2A",
    DarkBrown: "#5C4033",
    Chocolate: "#7B3F00",
    Coffee: "#6F4E37",
    Mocha: "#967969",
    Chestnut: "#954535",
    Tan: "#D2B48C",
    Camel: "#C19A6B",
    Taupe: "#483C32",
    Sand: "#C2B280",
    Terracotta: "#E2725B",
    Bronze: "#CD7F32",
    Copper: "#B87333",
    Sienna: "#A0522D",

    // Neon & Specialty
    NeonYellow: "#CCFF00",
    NeonGreen: "#39FF14",
    NeonPink: "#FF6EC7",
    NeonOrange: "#FF9933",
} as const;

// Categorized Color Families for Search & Filtering UI
export const COLOR_FAMILIES = {
    "All": Object.keys(COLORS),
    "Blacks & Grays": ["Black", "JetBlack", "Charcoal", "DarkSlate", "Slate", "Gray", "Grey", "AshGray", "Silver", "LightGray", "Platinum", "Gunmetal"],
    "Whites & Creams": ["White", "OffWhite", "Ivory", "Cream", "Beige", "Eggshell", "Pearl", "Alabaster", "Champagne", "Vanilla"],
    "Reds & Pinks": ["Red", "Crimson", "Scarlet", "Ruby", "Maroon", "Burgundy", "Wine", "BrickRed", "Coral", "Pink", "LightPink", "HotPink", "DeepPink", "Rose", "RoseGold", "Blush", "Magenta", "Fuchsia", "Salmon", "Peach"],
    "Blues & Aquas": ["Blue", "Navy", "MidnightBlue", "DarkBlue", "RoyalBlue", "Cobalt", "Indigo", "SkyBlue", "LightBlue", "BabyBlue", "PowderBlue", "Cyan", "Aqua", "Turquoise", "Teal", "SteelBlue", "Denim", "OceanBlue", "Sapphire", "ElectricBlue"],
    "Greens & Olives": ["Green", "DarkGreen", "ForestGreen", "Emerald", "Mint", "MintGreen", "Lime", "LimeGreen", "Olive", "OliveDrab", "Sage", "Khaki", "ArmyGreen", "Seafoam", "Jade", "Pistachio", "HunterGreen"],
    "Purples": ["Purple", "Violet", "Lavender", "Plum", "Lilac", "Mauve", "Eggplant", "Amethyst", "Grape", "Orchid", "Periwinkle"],
    "Yellows & Oranges": ["Yellow", "Lemon", "Gold", "Mustard", "Amber", "Orange", "DarkOrange", "CoralOrange", "Tangerine", "BurntOrange", "Rust", "Apricot", "Honey"],
    "Browns & Earth": ["Brown", "DarkBrown", "Chocolate", "Coffee", "Mocha", "Chestnut", "Tan", "Camel", "Taupe", "Sand", "Terracotta", "Bronze", "Copper", "Sienna"],
    "Neons": ["NeonYellow", "NeonGreen", "NeonPink", "NeonOrange"],
} as const;