"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
  ComposedChart,
  Area
} from "recharts";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { MetricCard, DataPanel } from "@/components/ui/professional";
import { useCategoryReport } from "@/hooks/queries/use-reports";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCurrency, cn } from "@/lib/utils";
import { motion } from "framer-motion";
import { 
  Layers, 
  TrendingUp, 
  Package, 
  BarChart3, 
  DollarSign, 
  Activity,
  ArrowRight
} from "lucide-react";
import { Badge } from "@/components/ui/badge";

const COLORS = [
  "#163625", // Brand Primary
  "#34d399", // Emerald
  "#818cf8", // Indigo
  "#fbbf24", // Amber
  "#f472b6", // Pink
  "#2dd4bf", // Teal
];

const item = {
  hidden: { opacity: 0, y: 10 },
  show: { opacity: 1, y: 0 },
};

export function CategoryReport({
  dateRange,
}: {
  dateRange: { from: Date | undefined; to: Date | undefined };
}) {
  const { data: categoryData, isLoading } = useCategoryReport(dateRange);

  if (isLoading) {
    return (
      <div className="space-y-8">
        <div className="grid gap-4 md:grid-cols-3">
          {[...Array(3)].map((_, i) => (
            <Skeleton key={i} className="h-28 rounded-[24px]" />
          ))}
        </div>
        <Skeleton className="h-[400px] rounded-[32px]" />
      </div>
    );
  }

  if (!categoryData) return null;

  const topCategory = categoryData.top_categories[0];

  return (
    <div className="space-y-8">
      <div className="grid gap-4 md:grid-cols-3">
        <motion.div variants={item}>
          <MetricCard
            label="Total Categories"
            value={categoryData.total_categories.toString()}
            icon={<Layers className="h-5 w-5" />}
            tone="brand"
            helper={`${categoryData.total_products} Active Products`}
          />
        </motion.div>
        <motion.div variants={item}>
          <MetricCard
            label="Leading Category"
            value={topCategory?.name || "N/A"}
            icon={<TrendingUp className="h-5 w-5" />}
            tone="emerald"
            helper={`${formatCurrency(parseFloat(topCategory?.total_sales || "0"))} total sales`}
          />
        </motion.div>
        <motion.div variants={item}>
          <MetricCard
            label="Category Depth"
            value={categoryData.total_categories > 0 ? Math.round(categoryData.total_products / categoryData.total_categories).toString() : "0"}
            icon={<Package className="h-5 w-5" />}
            tone="indigo"
            helper="Avg products per category"
          />
        </motion.div>
      </div>

      <div className="grid gap-8 lg:grid-cols-2">
        <motion.div variants={item}>
          <DataPanel title="Category Revenue" description="Total revenue generated by each product category.">
            <div className="h-[350px] pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={categoryData.sales_by_category}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis 
                    dataKey="category_name" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#94a3b8' }}
                  />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#94a3b8' }}
                    tickFormatter={(val) => `$${val}`}
                  />
                  <Tooltip contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }} />
                  <Bar dataKey="total_sales" radius={[8, 8, 0, 0]}>
                    {categoryData.sales_by_category.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </DataPanel>
        </motion.div>

        <motion.div variants={item}>
          <DataPanel title="Stock Valuation" description="Current inventory value across all categories.">
            <div className="h-[350px] pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <ComposedChart data={categoryData.stock_by_category}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis 
                    dataKey="category_name" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#94a3b8' }}
                  />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#94a3b8' }}
                    tickFormatter={(val) => `$${val}`}
                  />
                  <Tooltip contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }} />
                  <Area type="monotone" dataKey="total_value" fill="#163625" fillOpacity={0.05} stroke="#163625" strokeWidth={3} name="Total Value" />
                </ComposedChart>
              </ResponsiveContainer>
            </div>
          </DataPanel>
        </motion.div>
      </div>

      <motion.div variants={item}>
        <DataPanel title="Category Performance Overview" description="Detailed performance metrics for all business categories.">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="border-b border-slate-100 hover:bg-transparent">
                  <TableHead className="text-[10px] font-black uppercase tracking-widest text-slate-400 py-6">Category</TableHead>
                  <TableHead className="text-[10px] font-black uppercase tracking-widest text-slate-400 py-6">Product Count</TableHead>
                  <TableHead className="text-[10px] font-black uppercase tracking-widest text-slate-400 py-6">Units Sold</TableHead>
                  <TableHead className="text-[10px] font-black uppercase tracking-widest text-slate-400 py-6 text-right">Total Revenue</TableHead>
                  <TableHead className="text-[10px] font-black uppercase tracking-widest text-slate-400 py-6 text-right">Stock Value</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {categoryData.sales_by_category.map((category) => {
                  const stockInfo = categoryData.stock_by_category.find(
                    (s) => s.category_name === category.category_name
                  );
                  return (
                    <TableRow key={category.category_name} className="border-b border-slate-50 group hover:bg-slate-50/50 transition-colors">
                      <TableCell className="py-5">
                        <span className="text-xs font-black text-slate-700">{category.category_name}</span>
                      </TableCell>
                      <TableCell className="py-5">
                        <Badge variant="secondary" className="bg-slate-100 text-slate-500 border-none font-bold text-[10px]">
                          {category.unique_products} Products
                        </Badge>
                      </TableCell>
                      <TableCell className="py-5">
                        <div className="flex items-center gap-1.5">
                          <Activity className="h-3 w-3 text-slate-300" />
                          <span className="text-xs font-bold text-slate-500">{category.items_sold} Units</span>
                        </div>
                      </TableCell>
                      <TableCell className="py-5 text-right font-black text-brand-primary text-xs">
                        {formatCurrency(parseFloat(category.total_sales))}
                      </TableCell>
                      <TableCell className="py-5 text-right font-black text-slate-900 text-xs">
                        {formatCurrency(parseFloat(stockInfo?.total_value || "0"))}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        </DataPanel>
      </motion.div>
    </div>
  );
}
