# Generated by Django 4.2.11 on 2026-05-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_multi_branch'),
        ('inventory', '0017_product_ecommerce_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='branches.branch'),
        ),
    ]
