# Generated by Django 4.2.11 on 2026-05-11 08:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_stocktransfer_stocktransferitem_branchvariationstock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='retail_price',
        ),
        migrations.RemoveField(
            model_name='branchproduct',
            name='selling_price_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
        migrations.AddField(
            model_name='branchproduct',
            name='retail_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides product.retail_price for this branch.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='branchproduct',
            name='wholesale_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides product.wholesale_price for this branch.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='inventory.product')),
            ],
        ),
        # migrations.AlterUniqueTogether(
        #     name='gallery',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='productvariation',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='gallery',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='inventory.design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='inventory.design'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('design', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('design', 'color')},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='chest_size',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='waist_size',
        ),
    ]
