# Generated by Django 4.2.11 on 2026-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_rename_selling_price_product_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('design', 'size', 'color')},
        ),
    ]
