# Generated by Django 6.0.5 on 2026-06-12 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_category_product_wholesale_cutoff_and_settings'),
    ]

    operations = [
    ]
