# Generated by Django 4.2.11 on 2026-05-08 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_branch_invoice_counter_branch_invoice_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('entity_type', models.CharField(db_index=True, help_text="e.g. 'Product', 'Sale', 'Expense'", max_length=60)),
                ('entity_id', models.PositiveIntegerField(db_index=True, help_text='PK of the affected object')),
                ('entity_repr', models.CharField(blank=True, help_text='Human-readable representation, e.g. product name', max_length=200)),
                ('before_json', models.JSONField(blank=True, help_text='Snapshot of the entity before the change', null=True)),
                ('after_json', models.JSONField(blank=True, help_text='Snapshot of the entity after the change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
