# Generated by Django 4.2.11 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_backfill_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='invoice_counter',
            field=models.PositiveIntegerField(default=0, help_text='Auto-incrementing counter for invoice numbers.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, help_text='e.g. BR1. Used in invoice numbers like BR1-INV-000123.', max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
