import {
  BadgePercent,
  GalleryHorizontalEnd,
  House,
  LayoutGrid,
  MapPinned,
  Megaphone,
  PackageSearch,
} from "lucide-react";

export const ecommerceSettingsSections = [
  {
    title: "Overview",
    shortTitle: "Overview",
    description: "Review and open every storefront configuration area.",
    href: "/ecommerce-settings",
    icon: LayoutGrid,
    permission: null,
    accent: "from-slate-700 to-slate-950",
  },
  {
    title: "Home page",
    shortTitle: "Home",
    description: "Brand identity, landing page content, metrics, and footer.",
    href: "/ecommerce-settings/home-page",
    icon: House,
    permission: "manage_home_page_settings",
    accent: "from-emerald-500 to-teal-700",
  },
  {
    title: "Hero slides",
    shortTitle: "Hero",
    description: "Create, order, preview, and publish storefront banners.",
    href: "/ecommerce-settings/hero-slides",
    icon: GalleryHorizontalEnd,
    permission: "manage_hero_slides",
    accent: "from-violet-500 to-indigo-700",
  },
  {
    title: "Discounts",
    shortTitle: "Discounts",
    description: "Run storewide, category, or product-level promotions.",
    href: "/ecommerce-settings/discounts",
    icon: BadgePercent,
    permission: "manage_discounts",
    accent: "from-amber-500 to-orange-700",
  },
  {
    title: "Product sections",
    shortTitle: "Products",
    description: "Control featured collections and product placement.",
    href: "/ecommerce-settings/product-status",
    icon: PackageSearch,
    permission: "manage_product_status",
    accent: "from-sky-500 to-blue-700",
  },
  {
    title: "Delivery charges",
    shortTitle: "Delivery",
    description: "Set shipping rates for Dhaka, Gazipur, and other regions.",
    href: "/ecommerce-settings/delivery-charges",
    icon: MapPinned,
    permission: "manage_settings",
    accent: "from-cyan-500 to-cyan-800",
  },
  {
    title: "Promotional popups",
    shortTitle: "Popups",
    description: "Schedule targeted storefront popups and announcements.",
    href: "/ecommerce-settings/promotional-modals",
    icon: Megaphone,
    permission: "manage_promotional_modals",
    accent: "from-rose-500 to-pink-700",
  },
  {
    title: "Organize Landing Page",
    shortTitle: "Organizer",
    description: "Drag, drop, add, remove, and configure storefront layout sections dynamically.",
    href: "/ecommerce-settings/organize-landing-page",
    icon: LayoutGrid,
    permission: "manage_landing_page",
    accent: "from-blue-500 to-indigo-700",
  },
] as const;
