# Generated by Django 4.2.11 on 2026-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_multi_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='size',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='design_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
