# Generated by Django 6.0.5 on 2026-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_saleitem_applied_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, default='fixed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(blank=True, default='fixed', max_length=20, null=True),
        ),
    ]
