# Generated by Django 4.2.11 on 2026-05-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_multi_branch'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hr_branches',
            field=models.ManyToManyField(blank=True, help_text='If empty for HR role, all branches are accessible.', related_name='hr_users', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('hr', 'HR')], db_index=True, default='admin', max_length=20),
        ),
    ]
